---
- name: GreenPlum | Make sure users are present
  postgresql_user:
    name: "{{item.name}}"
    password: "{{ item.pass | default(omit) }}"
    encrypted: "{{ item.encrypted | default(omit) }}"
    port: "{{greenplum_port}}"
    state: present
    login_user: "{{greenplum_admin_user}}"
    login_db: postgres
  no_log: true
  become: yes
  become_user: "{{greenplum_admin_user}}"
  with_items: "{{greenplum_users}}"
  when: greenplum_users|length > 0

- name: GreenPlum | Make sure databases are present
  postgresql_db:
    name: "{{item.name}}"
    owner: "{{ item.owner | default(greenplum_database_owner) }}"
    encoding: "{{ item.encoding | default(greenplum_encoding) }}"
    port: "{{greenplum_port}}"
    template: "template0"
    state: present
    login_user: "{{greenplum_admin_user}}"
    maintenance_db: postgres
  become: yes
  become_user: "{{greenplum_admin_user}}"
  with_items: "{{greenplum_databases}}"
  when: greenplum_databases|length > 0

- name: GreenPlum | Update the user privileges
  postgresql_user:
    name: "{{item.name}}"
    db: "{{item.db | default(omit)}}"
    port: "{{greenplum_port}}"
    priv: "{{item.priv | default(omit)}}"
    state: present
    login_host: "{{item.host | default(omit)}}"
    login_user: "{{greenplum_admin_user}}"
    login_db: postgres
    role_attr_flags: "{{item.role_attr_flags | default(omit)}}"
  become: yes
  become_user: "{{greenplum_admin_user}}"
  with_items: "{{greenplum_user_privileges}}"
  when: greenplum_users|length > 0
