---

- import_tasks: install_RedHat.yml
  when: ansible_os_family == "RedHat"
  tags: [greenplum,greenplum-install]
  
- import_tasks: configure.yml
  tags: [greenplum,greenplum-configure]

- name: Set hostnames from ansible playbook
  hostname: name="{{ inventory_hostname }}"
  when: greenplum_init
  tags: [greenplum,greenplum-init]

- name: Init cluster
  shell: . /usr/lib/gpdb/greenplum_path.sh && /usr/lib/gpdb/bin/gpinitsystem -a -c gpinitsystem_config -h hostfile_gpinitsystem
  args:
    executable: /bin/bash
    chdir: ~gpadmin
  become_user: gpadmin
  register: init_script
  failed_when: init_script.rc > 1
  any_errors_fatal: true
  when: inventory_hostname in groups['greenplum-master'] and greenplum_init
  tags: [greenplum,greenplum-init]

