---

- import_tasks: install_RedHat.yml
  when: ansible_os_family == "RedHat"
  tags: [greenplum,greenplum-install]
  
- import_tasks: configure.yml
  tags: [greenplum,greenplum-configure]

- import_tasks: init.yml
  when: greenplum_init
  tags: [greenplum,greenplum-init]

- import_tasks: db_config.yml
  when: inventory_hostname in groups['greenplum-master']
  run_once: True
  tags: [greenplum,greenplum-db-configure]

- import_tasks: initdb.yml
  when: greenplum_init_db
  tags: [greenplum,greenplum-initdb]
