---

- name: reload sysctl
  command: /sbin/sysctl -p /etc/sysctl.conf
  ignore_errors: true

- name: restart system
  shell: ( /bin/sleep 5 ; /sbin/shutdown -r now "Ansible updates triggered" ) &
  async: 30
  poll: 0
  ignore_errors: true
  when: greenplum_reboot

- name: waiting for server to come back after reboot
  local_action: wait_for host={{ inventory_hostname }} port=22 state=started delay=20 timeout=900
  become: no
  when: greenplum_reboot

- name: reload pg_hba
  shell: kill -HUP $(head -1 "{{ item | dirname }}/postmaster.pid")
  when: item['changed']
  with_items: "{{ hba_handler_list }}"
  when: hba_handler_list is defined
  ignore_errors: True